name: Auto Label PR

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const number = context.payload.pull_request.number;

            let labels = [];

            if (title.startsWith("feat:")) labels.push("feat");
            else if (title.startsWith("fix:")) labels.push("fix");
            else if (title.startsWith("bug:")) labels.push("bug");
            else if (title.startsWith("refactor:")) labels.push("refactor");
            else if (title.startsWith("chore:")) labels.push("chore");
            else if (title.startsWith("version:")) labels.push("version");
            else if (title.startsWith("breaking:")) labels.push("version");

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                labels
              });
            }